
import { Injectable, OnModuleInit } from '@nestjs/common';
import { PrismaClient } from '@prisma/client';

@Injectable()
export class PrismaService extends PrismaClient implements OnModuleInit {
  // Explicitly declare properties that are dynamically generated by Prisma
  // to prevent TypeScript errors when the client hasn't been generated in the dev environment.
  public user: any;
  public subscriptionPayment: any;
  public formula: any;

  async onModuleInit() {
    // Cast to any to access $connect which might be missing in the stub type definition
    await (this as any).$connect();
  }
}
